[package]
name = "rustwebapp"
version = "0.1.0"
authors = ["superlogical"]

[dependencies]
iron="*"
persistent="*"
router = "*"
postgres = "*"
r2d2="*"
r2d2_postgres="*"
handlebars-iron="*"
rustc-serialize = "*"

[features]
integration_tests = []
